#!/usr/bin/env python3
"""Harvest the dotnet publish output into WiX Files.wxi (one component per file, auto GUIDs)."""
import os
import sys

def component_id(rel: str) -> str:
    safe = rel.replace("\\", "_").replace("/", "_").replace(".", "_").replace("-", "_").replace(" ", "_")
    return "c_" + safe

def file_id(rel: str) -> str:
    return component_id(rel).replace("c_", "f_", 1)

def main(publish_dir: str, out_path: str):
    publish_dir = os.path.abspath(publish_dir)
    rows = []
    for root, _dirs, files in os.walk(publish_dir):
        for f in sorted(files):
            full = os.path.join(root, f)
            rel = os.path.relpath(full, publish_dir)
            rows.append((rel, full))

    # map relative paths to the directory ids declared in Dirs.wxi
    def dir_attr(rel: str) -> str:
        parts = rel.replace("\\", "/").split("/")
        if parts[0] == "Assets" and len(parts) == 2:
            return "AssetsDir"
        if parts[0] == "Assets" and len(parts) == 3 and parts[1] == "sounds":
            return "SoundsDir"
        return "INSTALLFOLDER"

    lines = [
        '<Include xmlns="http://wixtoolset.org/schemas/v4/wxs">',
        "  <!-- AUTO-GENERATED by scripts/gen_wix_files.py — do not edit by hand. -->",
    ]
    for rel, full in rows:
        lines.append(f'  <Component Id="{component_id(rel)}" Directory="{dir_attr(rel)}" Guid="*">')
        lines.append(f'    <File Id="{file_id(rel)}" Name="{rel.replace(chr(92), "/").split("/")[-1]}" Source="{full}" />')
        lines.append("  </Component>")
    lines.append("</Include>")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Files.wxi written: {len(rows)} files -> {out_path}")

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
