#!/usr/bin/env python3
"""Harvest the dotnet publish output into WiX v4/v5 includes.

Emits BOTH:
  installer/Dirs.wxi   — dynamic nested directory tree under INSTALLFOLDER
  installer/Files.wxi  — one component per file, auto GUIDs, correct dir refs

Every file found under the publish dir is packaged, recursively — sprites,
sounds, fx, locales, anything. This is the fix for the "invisible cat" bug:
the v2.0.0 MSI shipped zero sprite PNGs, so the installed app had no frames
and rendered only the contact shadow.
"""
import os
import sys


def sanitize(seg: str) -> str:
    out = "".join(ch if ch.isalnum() else "_" for ch in seg)
    return out or "dir"


def dir_id(rel_dir: str) -> str:
    """Deterministic component-safe id for a relative directory ('' = root)."""
    if not rel_dir:
        return "INSTALLFOLDER"
    return "D_" + "_".join(sanitize(p) for p in rel_dir.replace("\\", "/").split("/"))


def component_id(rel: str) -> str:
    safe = rel.replace("\\", "_").replace("/", "_").replace(".", "_").replace("-", "_").replace(" ", "_")
    return "c_" + safe


def file_id(rel: str) -> str:
    return component_id(rel).replace("c_", "f_", 1)


def build_tree(dirs):
    """dirs: set of relative dir paths ('' excluded). Returns nested dict."""
    tree = {}
    for d in dirs:
        parts = d.replace("\\", "/").split("/")
        node = tree
        for p in parts:
            node = node.setdefault(p, {})
    return tree


def main(publish_dir: str, files_out: str, dirs_out: str):
    publish_dir = os.path.abspath(publish_dir)
    files = []
    dirs = set()
    for root, _dirs, fs in os.walk(publish_dir):
        for f in sorted(fs):
            full = os.path.join(root, f)
            rel = os.path.relpath(full, publish_dir)
            files.append((rel, full))
            rd = os.path.dirname(rel).replace("\\", "/")
            while rd:
                dirs.add(rd)
                rd = os.path.dirname(rd) if os.path.dirname(rd) != rd else ""

    # recursive emit that carries the accumulated path
    def emit_dir(children, pad, prefix):
        out = []
        for name, kids in sorted(children.items()):
            rel = f"{prefix}/{name}" if prefix else name
            did = dir_id(rel)
            if kids:
                out.append(f'{pad}<Directory Id="{did}" Name="{name}">')
                out.extend(emit_dir(kids, pad + "  ", rel))
                out.append(f"{pad}</Directory>")
            else:
                out.append(f'{pad}<Directory Id="{did}" Name="{name}" />')
        return out

    top = build_tree(dirs)
    lines = [
        '<Include xmlns="http://wixtoolset.org/schemas/v4/wxs">',
        "  <!-- AUTO-GENERATED by scripts/gen_wix_files.py — do not edit by hand. -->",
        '  <StandardDirectory Id="ProgramFiles64Folder">',
        '    <Directory Id="INSTALLFOLDER" Name="MeowCat">',
    ]
    lines.extend(emit_dir(top, "      ", ""))
    lines.extend([
        "    </Directory>",
        "  </StandardDirectory>",
        '  <StandardDirectory Id="ProgramMenuFolder">',
        '    <Directory Id="AppMenuDir" Name="MeowCat" />',
        "  </StandardDirectory>",
        '  <StandardDirectory Id="DesktopFolder" />',
        "</Include>",
    ])
    with open(dirs_out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    # ---- Files.wxi
    flines = [
        '<Include xmlns="http://wixtoolset.org/schemas/v4/wxs">',
        "  <!-- AUTO-GENERATED by scripts/gen_wix_files.py — do not edit by hand. -->",
    ]
    for rel, full in sorted(files):
        rd = os.path.dirname(rel).replace("\\", "/")
        did = dir_id(rd)
        name = os.path.basename(rel)
        flines.append(f'  <Component Id="{component_id(rel)}" Directory="{did}" Guid="*">')
        flines.append(f'    <File Id="{file_id(rel)}" Name="{name}" Source="{full}" />')
        flines.append("  </Component>")
    flines.append("</Include>")
    with open(files_out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(flines) + "\n")

    print(f"Dirs.wxi: {len(dirs)} dirs, Files.wxi: {len(files)} files -> {files_out}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
